### ISSUE TITLE
Event Creator is not getting reminder DM with netting details

### ISSUE THREAD

**Issue by DHaussermann** [mattermost/mattermost-plugin-mscalendar#111]
Sometimes the user does not receive the reminder posts when `Receive Reminders` is set to yes.
It seems like the event creator is the user that does not see the reminder. 

Steps:
- Login as a test user (organizer) and ensure `Receive Reminders` is set to yes
- Create a meeting event at least 15 minutes in the future and invite another user
- Open a 2nd browser session and login as the other user (attendee)
- Wait until there is less than 10 min left and the job runs (or run with slash command)
**Observed**: 
- Note that the test user did not receive the reminder post
- Note the other invited user did receive a reminder 
![EventReminder](https://user-images.githubusercontent.com/35588783/81034287-a25b7d00-8e64-11ea-9aa0-3b8438778b87.PNG)

**Comment by larkox** [comment]
I cannot reproduce this error. The underlying behaviour is:

1. Job runs every 5 minutes.
2. The job checks if the event starts between the following 5 to 10 minutes.
3. If the event is in the window, it will notify it.

Example:
1. Job runs at 5:00
2. Job checks if the event is starting between 5:05 and 5:10. If so, notify.

Same applies to the availability command.

**Comment by larkox** [comment]
@DHaussermann

**Comment by DHaussermann** [comment]
@larkox and @mickmister I feel like I'm misunderstanding something... Question:

Assuming that the user has change status notifications enabled and has already replied Yes in the invite DM - Should the user be receiving a specific reminder notification in addition to the status change notification?
If so would the user then receive 2 DM and would they be at the same time?

**Comment by larkox** [comment]
There are two different settings.
- Get confirmation when updating my status in mattermost
- Get reminder when an event is about to start

If both are activated, both may trigger a message, having the case where you get 2 DMs at the same time for the same event. Nevertheless, those 2 DMs will be different, and with different context (one will say that event X is about to start, and the other will say if you want to change your status during event X).

**Comment by DHaussermann** [comment]
I will look again today but I was seeing that I only get the 1 DM  about status change. @larkox  if I have the debug log going to the admin DM should I see any attempt to send the event reminder DM?

**Comment by larkox** [comment]
At the moment, the only debug messages are 4 different warnings.
- A warning if there is an error getting the availability for one user. (`Error getting availability for %s. err=%s`)
- A warning if there is a problem getting the user timezone (`notifyUpcomingEvents error getting timezone. err=%v`)
- A warning if there is a problem rendering the event (`notifyUpcomingEvent error rendering schedule item. err=%v`)
- A warning if threre is a problem creating the DM (`notifyUpcomingEvents error creating DM. err=%v`)

This is piggybacked in the SyncStatus job, so that job must be active. You will receive the reminder when that job runs (between 10 and 5 minutes before of the event starting).

The reasons to go out of the logic without a warning and without sending a DM are the following:
- ReceiveReminders setting is false
- The event is cancelled
- The event does not start in the time window (between 10 and 5 minutes after the job starts)

**Comment by DHaussermann** [comment]
@larkox I tested this again (build https://github.com/mattermost/mattermost-plugin-mscalendar/commit/d55078ab54f794a295558dd0f57b25a1ad63548d on master) and I only see the status change DM. 

I know the job is running and the setting is true. The event still exists because the job can see that I am not free. 

Maybe I'm misunderstanding something? Does this gif clarify anything? My understanding is that I should have received an additional DM here that does not mention status change.
cc @mickmister if you have any thoughts.

![MsCal](https://user-images.githubusercontent.com/35588783/82497907-1466cf80-9abd-11ea-8f0b-acdc06461d66.gif)

**Comment by DHaussermann** [comment]
@larkox Michael and I looked at this again and it working on my local now.

For now, no need to investigate further. I will close this issue if I don't see it occur again.

**Comment by DHaussermann** [comment]
No cases
