### ISSUE TITLE
store (and subsequently use) updated OAuth2 token when refreshed

### ISSUE THREAD

**Issue by levb** [mattermost/mattermost-plugin-mscalendar#15]
Presently, we store the original OAuth2 token and the refresh token, and then use both in all auth attempts, leading to extra refreshes, and also eventually the refresh token itself may expire.

We should hook into the OAUth2 flow, and if we get a new token back, store it back in the KV store and reuse until the next refresh.

**Comment by mickmister** [comment]
@levb The access tokens that Microsoft gives us last one hour, so it is not in our best interest to refresh them in advance. Furthermore, the refresh tokens do not expire because we are seen as a secure application in Microsoft's perspective. You can read more about this [here](https://docs.microsoft.com/en-us/azure/active-directory/develop/active-directory-configurable-token-lifetimes#token-lifetimes-with-confidential-client-refresh-tokens).

The only reason we would want to store a new refresh token, is if we also want to revoke the old one in Microsoft's system. I am 1/5 on updating/revoking them. I had begun writing the code to store the refresh tokens before fully realizing the information stated above, so adding the revoking functionality would be a simple addition.

**Comment by levb** [comment]
cc @crspeller looking for the best practice guidance.

**Comment by crspeller** [comment]
@levb @mickmister 
The golang oauth2 package does automatic refreshes. I would use that and let it handle: https://pkg.go.dev/golang.org/x/oauth2?tab=doc#Config.Client (this might be what we are already doing I didn't look)

The general practice I have seen for Oauth2 is the refresh token is eternal and you don't need to store the new one you are given. However I have seen Oauth2 implementations where storing the refresh token is necessary. Those actually break the spec so the package doesn't have nice support for it (but you can do it)

**Comment by mickmister** [comment]
@crspeller We are currently using the `oauth2` package's `Config.Client` to do the refreshes automatically (which is incredibly convenient btw). The question here is if we should be periodically revoking the refresh tokens that are in Microsoft's system, for an optional security measure on our end.

**Comment by levb** [comment]
I'll let one of you close the issue, thanks for following up and explaining.
