### ISSUE TITLE
When accessing the KVStore, use KVCompareAndSet to avoid issues with concurrent access

### ISSUE THREAD

**Issue by mickmister** [mattermost/mattermost-plugin-mscalendar#47]
#### Summary

In order to be tolerant of different HA nodes concurrently accessing the same KVStore value, we should use `KVCompareAndSet` throughout to ensure that the value has not changed during any update operation.

**Comment by mickmister** [comment]
@lieut-data Could we use `cluster.Mutex` to solve this case? There have been a few implementations of solving concurrent KV store access. `KVCompareAndSet` and [`KVModifyAtomic`](https://github.com/mattermost/mattermost-server/pull/13805/files) (which is in progress and does not use `KVCompareAndSet`).

I want to converge on one solution to guard against concurrent access to the KV store. Using `cluster.Mutex` seems practical because we can guard on the application level, and not rely on the database. It will be more certainly atomic and won't require retries.

**Comment by lieut-data** [comment]
@mickmister, eventually, everything falls back to the `KVCompareAndSet` operation under the covers. `cluster.Mutex` can be appropriate for a critical section, but may not be appropriate to safeguard access to lots of different key values (since you'd need a lock for each key value, which is overkill). 

I hadn't seen the `KVModifyAtomic` proposal before, but it will only be correct if it uses `KVCompareAndSet` (or the equivalent `KVSetWithOptions` and the `Atomic` bit). At the end of the day, it should just amount to a loop that retries a a modification until it succeeds (atomically), or the preconditions to make the change in the first place fail (because of a concurrent update).

So my gut is that this ticket is still valid as originally written.
